service: service-test-eg-plugin
provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1
  profile: ${opt:profile}

package:
  exclude:
    - node_modules/**
    - yarn.lock

custom:
  eventgateway:
    subdomain: something

plugins:
  - sls-plugin-eg

functions:
  foo:
    handler: foo.handler
    events:
      - eventgateway:
         event: http
         path: /
         method: GET
