language: node_js
sudo: false
node_js:
- 8
script:
- npm run lint
- npx istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
- npx codecov
before_deploy:
- snyk monitor --org=serverless
deploy:
  provider: npm
  email: services@serverless.com
  on:
    tags: true
  api_key:
    secure: sTjOXPM9p6J0LWf1u9AGMmc0uzWBLcpMXU9rk9azwgrFU3n3Ha7wPCY+UQAMnNnv9mQeV0OWzbm0uLS2BNkFU7Pd2Ioi03arlc/DjczuQ9n32jT7tUVKDeyr2y7ygX3PrUw3+cXAvc21Flca5dEQ5gXeoYhZwz91+u2hUPfi4VdhAnhJcEGVqcCoURWsQs2IpC4WE38V66EUFeET1FGUIN9VL9IWWNTvrtZSog8sbCvDB0+57l2H5KHHtv6RqFljfylJGF7IbIqguXMq8HKpm/6k/bPLYt1ztI9X/Fn7/FO8kc48BWn1wlpOwQD3upxrJxHnmAQDPewgLxmiA+8jl+GTWapsQfc7DuotN6rQorBEBWZl8x71EJD89iGcPgYygYMUxz8NLpYYNhjX02tNbLFQaNwp/uRhpizUjxsCic/m0aEmvn/SZ/jK28SKFT6uKw3T33rgWhU5wmYBlsRPIKAU8Zm36TZ3ZhmVRgqE7g5iM7/sRv9UfnbHsRYOyHypMqRQLeh9lnQlciHKW9iWpceh8t+DhSBREbieIwnVeygY2rJQ+K/3IFgRbu+5hoD/7unkSXAKapRG2km8OAL1JG3sOYuWgKPaNQbrs+BEnMKCuLSMbtBEtfOS5ZhefKP8ZjG+VTcczNDyh8E5MxETiURLdEX+3RVZ7/BC72lRjcs=
