language: node_js
sudo: false
node_js:
- 8
script:
- npm run lint
- npx istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
- npx codecov
deploy:
  provider: npm
  email: services@serverless.com
  on:
    tags: true
  api_key:
    secure: bP8qcBtnoJa8CL9pHPWzEx16rxEqlmtCQgWVlg1mq7Otis0FznipNNPYeXIA2GDedqHOtSvLZqMnzeIorxw9P7LiG3cJzRg2oopESzQIACiOVHj6fn20HtdgyAmyBmBiQ6ll0iH9mSkcRNny05lkOR6mDAEPncj5pvSMg6xxPHQPMO3GQQiqTwYacBVZGIMgTpYBNdsRUSV24kjc34YN++qHmfhfQaDskWkDbv7O2PgE9NH2UzAwe8w1AFtlJs8Pq0fCCmNsttNnHpIFXcBix3iPWAmu3KIY07Q7FDbGr+aSI30MhXtTSEXZ/QX1iFr3d8HXWl0OFhGhhEeeoGfwuLcDywgiPaT8NvNrBXwV5yFwgHYpz+z2VnW3TALAY65xfQUkeZ5n5/1pnianVXwWgH4MZlhifYLe+yu/aDmfjbOmb7Bn9qQerrheS57vJv1RYfO7+UEL0xBMlZ6Xh+LAW3U06FOky54O2/oztNsINmtBfRSnxxPlnaySaJ0TFmCy5H3tIhl20FUOCMk8cV6P2kW5pAe+P9Y6EkgYc2DeP6fWijSvkN6Uxyfy5LTCLSSar3/kqLu9nFKvg3jVIRdTVueSzQoQ6oJs0ZL6qoM0ngVmsJTK7mlD+wKVfpPhkOeMW/YE6XvzbOMHJbSWBworZgZ+6284eufBHWA4GBHStx4=
