language: node_js
sudo: false
node_js:
- 8
script:
- npm run lint
- npx istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
- npx codecov
deploy:
  provider: npm
  email: services@serverless.com
  on:
    tags: true
  api_key:
    secure: XEPTYTfuRXNEy5iabvcneRd+jmc/M34BejFOJvcinDsiolQj0gNaRomcLE1Dik3qPegcziUuu7Y2Ew+MoBo9pDp+mQkuBlcbBSAkSRhZ0ESHQTndr9JkxBMP5/U1oH81k07L6BdGxb3zuna6X6WlOuJAo4WGetPciR1A8FByGg2X+80Ph1uAYNwfwm8b8gyB72124HqKCZDLSZ/2qGOAAMRp7NpX97R5G588Em5KGKSWWiRGNfFXOk7uujj0AWDx77g5EzJPX3JNjfghKmipjA7vwkuSwa2cBDxjTs4jaSwPdKXYMGgroYkmPwTzQG8PmAlDlWty5mirpgw7KhEXfTm7jUrPm8MgyNw9j3cyW8jb6HMHsIn9R1ojgEJ3LIhaNoygi9k2J5hrR9iYd/jrNCu1B9ZcXdsqhB/dvgDCjcR0WLt25qahlecCh/08Q4PpYNeEIu4SqRDLLgbEsP/amFOQG4cEYNivyyzM55wQ94+LqYKwxmChdnMmaXRnktGo/u7oJ/g/vto4MBtoAPP5NfLdN4IxlzzelKA2919zHxSLJ4qvDh2K6xSlgkVl/C3jZL1o2PHxv6tMO4yquH0OJYj+d8l2aX9tFDaQ31ZyFWxDPGAmOqiBEM+s//KHR9sqEUwunniKEtYi6npuxQFVAIof13jPEnZBOiyPbvtSFfU=
