service: eg-users-example
provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1

custom:
  eventgateway:
    subdomain: <your subdomain>
    apikey: <your API key>

plugins:
  - "@serverless/serverless-event-gateway-plugin"

functions:
  getUser:
    handler: index.get
    events:
      - eventgateway:
          event: http
          method: GET
          path: /users/:id
  createUser:
    handler: index.post
    events:
      - eventgateway:
          event: http
          path: /users/:id
          method: POST
  deleteUser:
    handler: index.delete
    events:
      - eventgateway:
          event: http
          path: /users/:id
          method: DELETE
