service: eg-example-basic
provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1

package:
  exclude:
    - node_modules/**

custom:
  eventgateway:
    subdomain: <your subdomain>
    apikey: <your API key>

plugins:
  - "@serverless/serverless-event-gateway-plugin"

functions:
  hello:
    handler: index.handler
    events:
      - eventgateway:
          event: user.created
