service: event-gateway-plugin-example-basic
provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1

package:
  exclude:
    - node_modules/**

custom:
  eventgateway:
    subdomain: something

plugins:
  - serverless-event-gateway-plugin

functions:
  hello:
    handler: index.handler
    events:
      - eventgateway:
          event: http
          path: /
          method: GET
